projects:
  sailboatraces:
    schemaPath: amplify/backend/api/sailboatraces/build/schema.graphql
    includes:
      - graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: types/API.ts
        docsFilePath: graphql
        region: us-east-2
        apiId: null
        maxDepth: 2
extensions:
  amplify:
    version: 3
